server.port: 8080
spring:
  application.name: web-app
  profiles.active: dev
  cloud.vault:
    uri: http://localhost:8200
    authentication: APPROLE
    app-role:
      role_id: b3a95cf0-777b-6fb8-9e0d-5a7a2b09df28
      secret_id: 178b2649-c496-f02e-dd06-8e132badd41d
      role: web-app
      app-role-path: approle
  config.import: vault://secret/${spring.application.name}/${spring.profiles.active}/database

logging.level.root: INFO
logging.level.org.springframework.vault: DEBUG
